name: 'deploy-container'

on:
  push:
    branches:
      - master
    paths:
      - 'packages/container/**'  # only run when files inside container are changed

defaults:
  run:
    working-directory: packages/container

jobs:
  build-and-deploy:
    name: Build and Deploy Container
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - run: npm install

      - run: npm run build

      - uses: chrislennon/action-aws-cli@v1.1

      - name: Deploy to S3
        run: aws s3 sync dist s3://secret/container/latest
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
